import { describe, expect, it } from 'vitest';
import type { CostosImportacion, EstadoDominio, MapaComandos, TipoComando } from '../tipos';
import { TIPOS_COMANDO } from '../comandos/registro';
import { aplicarConstruccion } from '../motor/aplicar';
import {
  abastecer,
  abrirCaja,
  BLAZER_AZN_50,
  CHINO_ARENA_32,
  datosVenta,
  hacer,
  huella,
  nuevoEstado,
  OXFORD_M_AZC,
  pago,
  sobre,
} from './fixtures';

/**
 * Prueba genérica de atomicidad (PLAN 5.6.4, 7.14): para CADA comando del catálogo, con datos inválidos, el
 * estado antes y después en modo construcción es idéntico en profundidad y el resultado es un error de dominio.
 * El mapa es exhaustivo por tipos: si se agrega un comando, TypeScript exige su caso aquí.
 */
const NO = 'no-existe';
const costos: CostosImportacion = {
  flete: { moneda: 'USD', valor: 0 },
  seguro: { moneda: 'USD', valor: 0 },
  honorariosAgente: 0,
  bodegajePuerto: 0,
  transporteInterno: 0,
  otros: 0,
  otrosTributosAduaneros: 0,
  arancelPct: 0.15,
  ivaImportacionPct: 0.19,
  ivaSumaAlCosto: false,
};
const cliente = {
  nombres: 'Ana',
  apellidos: 'Ríos',
  documento: null,
  celular: '123',
  correo: null,
  cumpleanos: null,
  anioNacimiento: null,
  barrio: null,
  canalPreferido: 'whatsapp' as const,
  tratamiento: 'tu' as const,
  autorizacionDatos: { aceptada: false, fecha: '2026-09-30T10:00:00', canal: 'pos' as const },
  tallasDeclaradas: {},
  canalAlta: 'pos' as const,
  localRegistroId: null,
  registradoPorId: null,
};

const INVALIDOS = {
  'producto.crear': {
    productoId: 'pd_x',
    varianteIds: {},
    referencia: '',
    nombre: 'Prueba',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'x',
    proveedorId: 'pr_huameng',
    material: 'x',
    descripcion: 'x',
    precioVenta: 100_900,
    tarifaIva: 0.19,
    stockMinimo: 1,
    publicadoEnTienda: false,
    destacado: false,
    etiquetas: [],
    tallas: ['M', 'L'],
    colorIds: ['col_bla'],
    costoManual: null,
  },
  'producto.editar': { productoId: 'pd_cam_0142', cambios: { precioVenta: -5 } },
  'producto.eliminar': { productoId: 'pd_pan_0305', motivo: null },
  'variante.agregar': { productoId: 'pd_cam_0142', varianteId: 'va_x', talla: 'M', colorId: 'col_azc' },
  'variante.eliminar': { varianteId: CHINO_ARENA_32 },
  'color.crear': { colorId: 'col_x', nombre: 'Azul cielo', hex: '#123456', codigo: 'ZZZ' },
  'inventario.ajustar': {
    movimientoId: 'mv_x',
    varianteId: CHINO_ARENA_32,
    localId: 'usq',
    nuevaCantidad: -2,
    motivo: 'error',
    nota: null,
  },
  'traslado.solicitar': {
    trasladoId: 'tr_x',
    origenId: 'usq',
    destinoId: 'zr',
    lineas: [
      { varianteId: CHINO_ARENA_32, cantidad: 1 },
      { varianteId: OXFORD_M_AZC, cantidad: 1 },
    ],
    motivo: null,
    requiereAprobacion: true,
    solicitudId: 'so_x',
  },
  'traslado.despachar': { trasladoId: 'tr_pend' },
  'traslado.recibir': { trasladoId: 'tr_trans', recibidas: { [CHINO_ARENA_32]: 9 }, nota: null },
  'traslado.cancelar': { trasladoId: 'tr_trans', motivo: '' },
  'conteo.iniciar': { conteoId: 'cf_x', localId: 'p93', categorias: null },
  'conteo.guardar': { conteoId: 'cf_1', cantidades: { [CHINO_ARENA_32]: 2, [NO]: 1 } },
  'conteo.aplicar': { conteoId: 'cf_1', motivos: {} },
  'conteo.cancelar': { conteoId: NO },
  'caja.abrir': { sesionId: 'sc_x', localId: 'usq', baseInicial: 1, por: null },
  'caja.egreso': {
    egresoId: 'eg_x',
    sesionId: 'sc_usq',
    concepto: 'x',
    valor: 999_999_999,
    categoria: 'otros',
  },
  'caja.cerrar': {
    sesionId: 'sc_usq',
    denominaciones: { '50000': 1 },
    efectivoContado: 2,
    observacion: null,
    por: null,
  },
  'caja.revisarCierre': { sesionId: 'sc_usq', nota: null },
  'venta.registrar': datosVenta('vt_x', {
    lineas: [
      { varianteId: CHINO_ARENA_32, cantidad: 1, precioLista: null, descuento: null },
      { varianteId: OXFORD_M_AZC, cantidad: 1, precioLista: null, descuento: null },
    ],
    clienteNuevo: {
      ...cliente,
      celular: '3001234567',
      autorizacionDatos: { ...cliente.autorizacionDatos, aceptada: true },
      clienteId: 'cl_x',
    },
    pagos: [pago('efectivo', 419_800)],
  }),
  'venta.editar': { ventaId: 'vt_1', cambios: { vendedorId: 'em_lsmendez' } },
  'venta.anular': { ventaId: 'vt_1', motivo: 'x', reembolso: null, notaCreditoId: null, solicitudId: null },
  'venta.abonar': { ventaId: 'vt_s', pago: pago('nequi', 999_999_999) },
  'separado.cancelar': { ventaId: 'vt_s', destinoAbonos: 'reembolso', reembolso: null },
  'devolucion.registrar': {
    devolucionId: 'dv_x',
    ventaId: 'vt_1',
    lineas: [{ lineaId: 'vt_1-l1', cantidad: 5, reingresa: true }],
    motivo: 'x',
    compensacion: 'reembolso',
    reembolso: { medio: 'nequi', sesionCajaId: null },
    notaCreditoId: null,
    clienteNuevo: null,
  },
  'pago.conciliar': {
    refs: [
      { tipo: 'pago_venta', ventaId: 'vt_1', pagoId: 'vt_1-p1' },
      { tipo: 'movimiento', movimientoId: NO },
    ],
    conciliado: true,
  },
  'aprobacion.solicitar': {
    solicitudId: 'so_y',
    datos: {
      tipo: 'descuento',
      localId: 'usq',
      vendedorId: 'em_scardenas',
      varianteIds: [BLAZER_AZN_50],
      valorLista: 789_900,
      porcentaje: 0.1,
      valorFinal: 710_910,
      motivo: 'x',
    },
  },
  'bono.vender': {
    bonoId: 'bo_x',
    codigo: null,
    valor: 100_000,
    localId: 'usq',
    pago: pago('efectivo', 90_000),
    vence: '2026-12-31',
  },
  'datafono.registrarAbono': {
    abonoId: 'ad_x',
    localId: 'zr',
    ventasDe: '2026-09-30',
    fecha: '2026-10-01',
    cuentaDestinoId: 'cta_corriente',
  },
  'aprobacion.resolver': { solicitudId: NO, decision: 'aprobada', nota: null },
  'cliente.crear': { clienteId: 'cl_y', datos: cliente },
  'cliente.editar': { clienteId: 'cl_andres_gutierrez', cambios: { celular: '3108765432' } },
  'cliente.eliminar': { clienteId: NO, motivo: null },
  'cliente.nota': { notaId: 'nc_x', clienteId: 'cl_andres_gutierrez', texto: '  ' },
  'mensaje.registrar': {
    mensajes: [
      {
        id: 'ms_1',
        ts: '2026-09-30T10:00:00',
        canal: 'wechat',
        destinatario: { tipo: 'libre', refId: null, nombre: 'Lily', telefono: null, correo: null },
        idioma: 'en',
        tratamiento: 'tu',
        asunto: null,
        cuerpo: 'Hi',
        origen: { tipo: 'importacion', id: null },
      },
      {
        id: 'ms_2',
        ts: '2026-09-30T10:00:00',
        canal: 'whatsapp',
        destinatario: { tipo: 'libre', refId: null, nombre: 'Óscar', telefono: null, correo: null },
        idioma: 'es',
        tratamiento: 'usted',
        asunto: null,
        cuerpo: 'Hola',
        origen: { tipo: 'importacion', id: null },
      },
    ],
  },
  'proveedor.crear': {
    proveedorId: 'pr_x',
    datos: {
      tipo: 'local',
      nombre: '',
      nombreCorto: 'x',
      nit: null,
      ciudad: 'Bogotá',
      pais: 'Colombia',
      moneda: 'COP',
      condicionesPago: 'x',
      diasEntregaPactados: null,
      categoriaLocal: null,
      localId: null,
      categoriasProducto: [],
      calificacion: 3,
      contactoIds: [],
      nota: null,
    },
  },
  'proveedor.editar': { proveedorId: 'pr_huameng', cambios: { calificacion: 9 as 1 } },
  'proveedor.eliminar': { proveedorId: 'pr_huameng', motivo: null },
  'contacto.crear': {
    contactoId: 'co_x',
    datos: {
      nombre: 'x',
      empresa: 'x',
      rol: 'otro',
      proveedorId: null,
      correo: 'malo',
      whatsapp: '+57 300 000 0000',
      pais: 'Colombia',
      idioma: 'es',
      tratamiento: 'usted',
      canalPreferido: 'whatsapp',
      wechat: null,
    },
  },
  'contacto.editar': { contactoId: 'co_lily_chen', cambios: { whatsapp: 'abc' } },
  'contacto.eliminar': { contactoId: NO },
  'importacion.crear': {
    importacionId: 'im_x',
    numero: null,
    proveedorId: 'pr_huameng',
    moneda: 'USD',
    tasaPedido: 3_950,
    fechaPedido: '2026-09-01',
    carga: { tipo: 'consolidada', m3: 1 },
    puertoOrigen: 'x',
    puertoDestino: 'Buenaventura',
    lineas: [
      {
        id: 'l1',
        productoId: 'pd_cam_0142',
        cantidades: { [CHINO_ARENA_32]: 3 },
        costoUnitarioOrigen: 1_140,
      },
    ],
    contactoIds: [],
    costos,
    metodoProrrateo: 'valor',
    origenSugerencia: null,
    nota: null,
  },
  'importacion.editar': { importacionId: 'im_1', cambios: { numero: 'IMP-2099-99' } },
  'importacion.eliminar': { importacionId: 'im_1', motivo: null },
  'importacion.cambiarEstado': {
    importacionId: 'im_1',
    estado: 'recibido_bodega',
    fecha: '2026-09-30',
    nota: null,
    origen: 'panel',
    autor: null,
  },
  'importacion.actualizarHitos': { importacionId: 'im_1', estimadas: { en_puerto: '2020-01-01' } },
  'importacion.actualizarCostos': {
    importacionId: 'im_1',
    costos: { ...costos, honorariosAgente: -1 },
    metodoProrrateo: 'valor',
  },
  'importacion.aplicarCostos': { importacionId: 'im_1', tasaCosteo: -1 },
  'importacion.registrarPago': {
    importacionId: 'im_1',
    cxpId: 'im_1-cxp-saldo',
    abonoId: 'ab_x',
    centavos: 999_999_999,
    tasa: 3_950,
    fecha: '2026-09-30',
    cuentaId: 'cta_corriente',
  },
  'importacion.documento': {
    importacionId: 'im_1',
    documento: { tipo: 'bl', numero: 'x', nombreArchivo: '', estado: 'recibido', fecha: null },
  },
  'importacion.recibir': {
    importacionId: 'im_1',
    fecha: '2026-09-30',
    lineas: {},
    nota: null,
    distribucion: [
      { trasladoId: 'tr_d1', destinoId: 'usq', lineas: [{ varianteId: OXFORD_M_AZC, cantidad: 30 }] },
      { trasladoId: 'tr_d2', destinoId: 'zr', lineas: [{ varianteId: OXFORD_M_AZC, cantidad: 30 }] },
    ],
  },
  'cxp.crear': {
    cxpId: 'cp_x',
    datos: {
      categoria: 'otro',
      terceroNombre: 'x',
      proveedorId: null,
      empleadoId: null,
      concepto: 'x',
      localId: null,
      moneda: 'COP',
      valor: 0,
      fechaEmision: '2026-09-30',
      fechaVencimiento: '2026-09-30',
      documento: null,
      soporte: null,
      nota: null,
    },
  },
  'cxp.editar': { cxpId: 'im_1-cxp-anticipo', cambios: { moneda: 'COP' } },
  'cxp.eliminar': { cxpId: 'im_1-cxp-anticipo', motivo: null },
  'cxp.programar': { cxpId: 'im_1-cxp-anticipo', fecha: '2026/10/01' },
  'cxp.pagar': {
    cxpId: 'im_1-cxp-saldo',
    abonoId: 'ab_y',
    fecha: '2026-09-30',
    valorCOP: null,
    centavos: null,
    tasa: null,
    cuentaId: 'cta_corriente',
    medio: 'transferencia',
    soporte: null,
  },
  'cuenta.crear': {
    cuentaId: 'cta_x',
    datos: {
      nombre: '',
      tipo: 'banco',
      localId: null,
      entidad: null,
      numeroEnmascarado: null,
      saldoInicial: 0,
      fechaSaldoInicial: '2026-09-30',
      orden: 9,
    },
  },
  'cuenta.editar': { cuentaId: 'cta_corriente', cambios: { saldoInicial: 1.5 } },
  'cuenta.transferir': {
    transferenciaId: 'tf_x',
    origenId: 'cta_corriente',
    destinoId: 'cta_corriente',
    valor: 1,
    fecha: '2026-09-30',
    descripcion: 'x',
  },
  'cuenta.movimiento': {
    movimientoId: 'mc_x',
    cuentaId: 'cta_corriente',
    valor: 0,
    tipo: 'ajuste',
    fecha: '2026-09-30',
    descripcion: 'x',
  },
  'gasto.registrar': {
    gastoId: 'gs_x',
    datos: {
      fecha: '2026-09-30',
      localId: null,
      categoria: 'otros',
      concepto: 'x',
      valor: 100,
      iva: 200,
      proveedorId: null,
      soporte: null,
      documento: null,
    },
    pago: { tipo: 'inmediato', cuentaId: 'cta_corriente', medio: 'x' },
  },
  'gasto.editar': { gastoId: 'eg_1-g', cambios: { valor: 1 } },
  'gasto.eliminar': { gastoId: 'eg_1-g', motivo: null },
  'gastoRecurrente.crear': {
    recurrenteId: 'gr_x',
    datos: {
      nombre: 'x',
      categoria: 'otros',
      localId: null,
      valor: 1,
      iva: 0,
      diaDelMes: 31,
      proveedorId: null,
      formaPago: 'cuenta_por_pagar',
      diasPlazo: 0,
      cuentaId: null,
      desde: '2026-09',
      hasta: null,
      activo: true,
    },
  },
  'gastoRecurrente.editar': { recurrenteId: 'gr_internet', cambios: { cuentaId: NO } },
  'gastoRecurrente.eliminar': { recurrenteId: NO },
  'gastoRecurrente.generarMes': { mes: '2026-13x' },
  'empleado.crear': {
    empleadoId: 'em_x',
    contratoId: 'ct_x',
    datos: {
      slug: 'nomina',
      nombres: 'x',
      apellidos: 'x',
      documento: { tipo: 'CC', numero: '1' },
      fechaNacimiento: null,
      cargo: 'vendedor',
      localId: 'usq',
      fechaIngreso: '2026-09-01',
      fechaRetiro: null,
      celular: '3001234567',
      correo: 'a@b.example',
      contactoEmergencia: { nombre: 'x', parentesco: 'x', celular: '3001234567' },
      afiliaciones: { eps: 'x', pension: 'x', cesantias: 'x', arl: 'x', caja: 'x' },
      cuentaPago: { entidad: 'x', tipo: 'ahorros', numeroEnmascarado: 'x' },
    },
    contrato: {
      tipo: 'laboral',
      modalidadLaboral: 'indefinido',
      inicio: '2026-09-01',
      fin: null,
      salarioBase: 1_000_000,
      honorarios: null,
      jornadaSemanalHoras: 42,
      riesgoArl: 1,
      esquemaComisionId: null,
      periodicidadPago: 'quincenal',
      retencionFuente: null,
      verificacionesPila: [],
    },
  },
  'empleado.editar': { empleadoId: 'em_scardenas', cambios: { slug: 'otro' } },
  'empleado.retirar': { empleadoId: 'em_scardenas', fecha: '2000-01-01', motivo: 'x' },
  'contrato.reemplazar': {
    empleadoId: 'em_scardenas',
    contratoId: 'ct_x',
    desde: '2026-10-01',
    contrato: {
      tipo: 'laboral',
      modalidadLaboral: 'indefinido',
      inicio: '2026-10-01',
      fin: null,
      salarioBase: 10,
      honorarios: null,
      jornadaSemanalHoras: 42,
      riesgoArl: 1,
      esquemaComisionId: null,
      periodicidadPago: 'quincenal',
      retencionFuente: null,
      verificacionesPila: [],
    },
  },
  'esquemaComision.crear': {
    esquemaId: 'esq_x',
    datos: { nombre: 'x', base: 'base_sin_iva', componentes: [{ tipo: 'porcentaje', porcentaje: 0.5 }] },
  },
  'esquemaComision.editar': { esquemaId: 'esq_3pct', cambios: { componentes: [] } },
  'esquemaComision.eliminar': { esquemaId: 'esq_3pct' },
  'meta.fijar': { metaId: 'mt_x', localId: 'bod', mes: '2026-10', valor: 1 },
  'turno.asignar': {
    turnoId: 'tu_x',
    empleadoId: 'em_scardenas',
    localId: 'usq',
    fecha: '2026-09-30',
    tipo: 'cierre',
    inicio: '12:00',
    fin: '20:00',
    descansoMin: 60,
    aceptarExceso: true,
  },
  'turno.mover': {
    turnoId: 'tu_1',
    fecha: '2026-09-30',
    empleadoId: 'em_scardenas',
    localId: 'usq',
    tipo: 'apertura',
    inicio: '25:00',
    fin: '18:00',
    aceptarExceso: false,
  },
  'turno.eliminar': { turnoId: NO },
  'turno.copiarSemana': {
    localId: 'usq',
    lunesOrigen: '2026-09-28',
    lunesDestino: '2026-10-06',
    aceptarExceso: false,
  },
  'marcacion.registrar': {
    marcacionId: 'ma_x',
    empleadoId: 'em_scardenas',
    localId: 'usq',
    tipo: 'entrada',
    ts: '2026-09-30T11:00:00',
  },
  'marcacion.corregir': { marcacionId: 'ma_1', ts: '2026-09-30T19:00:00', nota: ' ' },
  'marcacion.eliminar': { marcacionId: 'ma_1', nota: '' },
  'novedad.registrar': {
    novedadId: 'nv_x',
    datos: {
      empleadoId: 'em_scardenas',
      tipo: 'vacaciones',
      desde: '2026-10-10',
      hasta: '2026-10-01',
      remunerada: true,
      soporte: null,
      nota: null,
    },
  },
  'novedad.editar': { novedadId: NO, cambios: {} },
  'novedad.eliminar': { novedadId: NO },
  'pila.verificar': { contratoId: 'ct_scardenas_1', periodo: '2026-09', verificada: true, soporte: null },
  'nomina.aprobar': {
    liquidacionId: 'lq_x',
    periodo: { inicio: '2026-09-16', fin: '2026-09-30', tipo: 'quincenal', etiqueta: 'x' },
    exoneracion114: true,
    insumos: null,
  },
  'nomina.pagar': { liquidacionId: 'lq_1', fecha: '2026-09-30', cuentaId: NO },
  'nomina.anularAprobacion': { liquidacionId: NO },
  'evento.crear': {
    eventoId: 'ev_x',
    datos: {
      tipo: 'cita',
      subtipo: 'asesoria',
      titulo: 'x',
      inicio: '2026-10-02T10:00:00',
      fin: '2026-10-01T10:00:00',
      todoElDia: false,
      localId: null,
      clienteId: null,
      empleadoId: null,
      descripcion: null,
      recordatorioMin: null,
    },
  },
  'evento.editar': { eventoId: 'ev_cita_medidas_penuela', cambios: { titulo: '' } },
  'evento.eliminar': { eventoId: NO },
  'factura.emitir': {
    facturaId: 'fa_x',
    ventaId: 'vt_1',
    tipo: 'factura_electronica',
    adquirente: {
      tipo: 'consumidor_final',
      clienteId: null,
      nombre: 'Consumidor final',
      documento: null,
      correo: null,
    },
  },
  'factura.avanzarEstado': { facturaId: 'fa_1', estado: 'aceptada' },
  'notaCredito.emitir': { notaId: 'ncr_x', facturaId: 'fa_1', devolucionId: NO, motivo: 'x' },
  'notaCredito.avanzarEstado': { notaId: NO, estado: 'enviada' },
  'empresa.editar': { cambios: { nit: '123' } },
  'local.crear': {
    localId: 'lo_x',
    datos: {
      codigo: 'USQ',
      nombre: 'x',
      tipo: 'tienda_calle',
      vende: true,
      direccion: 'x',
      zona: 'x',
      horario: { 0: null, 1: null, 2: null, 3: null, 4: null, 5: null, 6: null },
      horarioFestivo: null,
      cuentaCajaId: null,
      arriendoMensual: 0,
      areaM2: 1,
      orden: 9,
    },
  },
  'local.editar': { localId: 'usq', cambios: { nombre: '' } },
  'local.eliminar': { localId: 'usq', motivo: null },
  'tasa.registrar': { tasaId: 'tasa_x', moneda: 'USD', fecha: '2026-09-30', valor: 0 },
  'tasa.editar': { tasaId: 'tasa_usd_inicial', valor: 4_000, fecha: '2030-01-01' },
  'tasa.eliminar': { tasaId: 'tasa_usd_inicial' },
  'parametros.editar': { seccion: 'ventas', cambios: { descuentoMaximoVendedor: 2 } },
  'resolucion.editar': { resolucionId: 'res_fe', cambios: { desde: 10, hasta: 5 } },
  'usuario.crear': {
    usuarioId: 'u_x',
    datos: {
      nombre: 'x',
      correo: 'malo',
      iniciales: 'X',
      rol: 'vendedor',
      empleadoId: null,
      localFijoId: null,
      activo: true,
    },
  },
  'usuario.editar': { usuarioId: 'u_dueno', cambios: { rol: 'vendedor' } },
  'usuario.eliminar': { usuarioId: 'u_dueno' },
} satisfies { [K in TipoComando]: MapaComandos[K] };

/** Estado con datos en casi todas las tablas, para que las validaciones lleguen lejos. */
function estadoRico(): EstadoDominio {
  const e = nuevoEstado();
  abastecer(e, CHINO_ARENA_32, 'usq', 4);
  abastecer(e, BLAZER_AZN_50, 'usq', 2);
  abrirCaja(e, 'usq');
  hacer(
    e,
    'venta.registrar',
    datosVenta('vt_1', {
      facturaInmediata: {
        facturaId: 'fa_1',
        tipo: 'factura_electronica',
        adquirente: {
          tipo: 'consumidor_final',
          clienteId: null,
          nombre: 'Consumidor final',
          documento: null,
          correo: null,
        },
      },
    }),
  );
  hacer(
    e,
    'venta.registrar',
    datosVenta('vt_s', {
      tipo: 'separado',
      clienteId: 'cl_andres_gutierrez',
      pagos: [pago('nequi', 50_000)],
      fechaLimiteSeparado: '2026-10-20',
    }),
  );
  hacer(e, 'traslado.solicitar', {
    trasladoId: 'tr_pend',
    origenId: 'usq',
    destinoId: 'zr',
    lineas: [{ varianteId: CHINO_ARENA_32, cantidad: 1 }],
    motivo: null,
    requiereAprobacion: true,
    solicitudId: 'so_t',
  });
  hacer(e, 'traslado.solicitar', {
    trasladoId: 'tr_trans',
    origenId: 'usq',
    destinoId: 'zr',
    lineas: [{ varianteId: CHINO_ARENA_32, cantidad: 1 }],
    motivo: null,
    requiereAprobacion: false,
    solicitudId: null,
  });
  hacer(e, 'traslado.despachar', { trasladoId: 'tr_trans' });
  hacer(e, 'conteo.iniciar', { conteoId: 'cf_1', localId: 'p93', categorias: ['pantalones'] });
  hacer(e, 'conteo.guardar', { conteoId: 'cf_1', cantidades: { [CHINO_ARENA_32]: 2 } });
  hacer(e, 'caja.egreso', {
    egresoId: 'eg_1',
    sesionId: 'sc_usq',
    concepto: 'Domicilio',
    valor: 10_000,
    categoria: 'transporte',
  });
  hacer(e, 'importacion.crear', {
    importacionId: 'im_1',
    numero: null,
    proveedorId: 'pr_huameng',
    moneda: 'USD',
    tasaPedido: 3_950,
    fechaPedido: '2026-06-01',
    carga: { tipo: 'consolidada', m3: 6 },
    puertoOrigen: 'Shenzhen (Yantian)',
    puertoDestino: 'Buenaventura',
    lineas: [
      { id: 'l1', productoId: 'pd_cam_0142', cantidades: { [OXFORD_M_AZC]: 48 }, costoUnitarioOrigen: 1_140 },
    ],
    contactoIds: [],
    costos,
    metodoProrrateo: 'valor',
    origenSugerencia: null,
    nota: null,
  });
  hacer(e, 'importacion.cambiarEstado', {
    importacionId: 'im_1',
    estado: 'nacionalizado',
    fecha: '2026-09-20',
    nota: null,
    origen: 'panel',
    autor: null,
  });
  hacer(e, 'importacion.registrarPago', {
    importacionId: 'im_1',
    cxpId: 'im_1-cxp-anticipo',
    abonoId: 'ab_1',
    centavos: 10_000,
    tasa: 3_950,
    fecha: '2026-09-20',
    cuentaId: 'cta_corriente',
  });
  hacer(e, 'turno.asignar', {
    turnoId: 'tu_1',
    empleadoId: 'em_scardenas',
    localId: 'usq',
    fecha: '2026-09-30',
    tipo: 'apertura',
    inicio: '10:00',
    fin: '18:00',
    descansoMin: 60,
    aceptarExceso: false,
  });
  hacer(
    e,
    'marcacion.registrar',
    {
      marcacionId: 'ma_1',
      empleadoId: 'em_scardenas',
      localId: 'usq',
      tipo: 'entrada',
      ts: '2026-09-30T10:01:00',
    },
    { rol: 'sistema' },
  );
  hacer(e, 'nomina.aprobar', {
    liquidacionId: 'lq_1',
    periodo: {
      inicio: '2026-09-16',
      fin: '2026-09-30',
      tipo: 'quincenal',
      etiqueta: '2.ª quincena de septiembre de 2026',
    },
    exoneracion114: true,
    insumos: null,
  });
  return e;
}

describe('atomicidad de los manejadores (5.6.4)', () => {
  it('el catálogo tiene un manejador por comando (108)', () => {
    expect(TIPOS_COMANDO).toHaveLength(108);
    expect(new Set(TIPOS_COMANDO)).toEqual(new Set(Object.keys(INVALIDOS)));
  });

  const base = estadoRico();
  const huellaBase = huella(base);
  for (const tipo of TIPOS_COMANDO) {
    it(`${tipo}: con datos inválidos no cambia nada`, () => {
      const e = structuredClone(base);
      const r = aplicarConstruccion(e, sobre(tipo, INVALIDOS[tipo] as never, { ts: '2026-09-30T16:00:00' }));
      expect(r.ok, JSON.stringify(r)).toBe(false);
      if (!r.ok) expect(r.error.mensaje.length).toBeGreaterThan(5);
      expect(huella(e)).toBe(huellaBase);
    });
  }

  it('un rol sin permiso tampoco cambia nada', () => {
    const e = structuredClone(base);
    const r = aplicarConstruccion(
      e,
      sobre(
        'venta.anular',
        {
          ventaId: 'vt_1',
          motivo: 'x',
          reembolso: { medio: 'nequi', sesionCajaId: null },
          notaCreditoId: 'ncr_9',
          solicitudId: null,
        },
        { rol: 'vendedor' },
      ),
    );
    expect(r).toMatchObject({ ok: false, error: { codigo: 'SIN_PERMISO' } });
    expect(huella(e)).toBe(huellaBase);
  });
});
