/** Copy de la interfaz de Inicio (D1). Español de Colombia, lenguaje del comerciante (PLAN 8.11.4). */

export const TXT = {
  titulo: 'Inicio',
  saludos: { manana: 'Buenos días', tarde: 'Buenas tardes', noche: 'Buenas noches' },
  sinVentasHoy: 'Todavía no hay ventas registradas hoy',
  error: {
    titulo: 'No pudimos mostrar esta parte',
    texto: 'Tus datos están bien guardados; el problema es solo de esta tarjeta.',
    reintentar: 'Intentar de nuevo',
  },
  kpis: { aria: 'Indicadores del negocio' },
  grafico: {
    titulo: 'Ventas de los últimos 30 días por local',
    verVentas: 'Ver ventas',
    mejorDia: 'Mejor día',
    promedio: 'Por día',
    total: 'Total',
    aportoMas: 'Aportó más',
    aporteDe: 'Su aporte',
  },
  alertas: {
    titulo: 'Requiere tu atención',
    nuevo: 'Nuevo',
    descartar: 'Descartar alerta',
    verTodas: (n: number) => `Ver todas (${n})`,
    verMenos: 'Ver menos',
    vacioTitulo: 'Todo en orden por ahora',
    vacioTexto: 'No hay nada pendiente: ni stock bajo, ni pagos por vencer, ni cierres con diferencia.',
    descartadas: (n: number) => (n === 1 ? 'Descartaste 1 alerta' : `Descartaste ${n} alertas`),
    restaurar: 'Volver a mostrarlas',
    aprobar: 'Aprobar',
    rechazar: 'Rechazar',
    aprobada: 'Aprobaste el descuento: el vendedor ya puede cobrar.',
    rechazada: 'Rechazaste el descuento. El vendedor lo ve en su punto de venta.',
  },
  locales: {
    titulo: 'Tus tres locales',
    ventas: 'Ventas del mes',
    margen: 'Margen',
    ticket: 'Ticket promedio',
    unidades: 'Unidades',
    meta: 'Meta del mes',
    sinMeta: 'Sin meta definida para este mes',
    ultimoCierre: 'Último cierre de caja',
    sinCierre: 'Aún sin cierres de caja',
    seleccionado: 'Filtro activo',
  },
  top: {
    titulo: 'Más vendidos',
    medida: { unidades: 'Unidades', valor: 'Ventas', margen: 'Margen' },
    vacioTitulo: 'Aún no hay ventas este mes',
    vacioTexto: 'Apenas registres la primera venta del mes, aquí verás lo que más sale.',
    verTodo: 'Ver análisis',
  },
  dormidos: {
    titulo: 'Sin movimiento en 60 días',
    vacioTitulo: 'Nada dormido en el inventario',
    vacioTexto: 'Todas las referencias con existencias se vendieron en los últimos 60 días.',
    verTodo: 'Ver rotación',
  },
  eventos: {
    titulo: 'Próximos eventos',
    vacioTitulo: 'Sin eventos próximos',
    vacioTexto: 'No hay citas, vencimientos ni llegadas de mercancía en los próximos 60 días.',
    verTodo: 'Ver calendario',
  },
  hallazgo: {
    eyebrow: 'Hallazgo de la semana',
    verAnalisis: 'Ver más en Análisis',
    verDetalle: 'Ver el detalle',
  },
} as const;
