/**
 * Copy de la app del dueño (`/app`, E1). Español de Colombia, tuteo, frases cortas: se lee en el celular, de pie,
 * con una mano. Ninguna cifra va aquí (siempre salen de los selectores y de `lib/formato`).
 */
export const TXT = {
  hoy: {
    titulo: 'Hoy',
    vendidoHoy: 'Vendido hoy',
    vendidoAyer: 'Vendido ayer',
    antesDeAbrir: 'Todavía no abren los locales',
    ventasEn: (n: number) => (n === 1 ? '1 venta' : `${n} ventas`),
    metaMes: 'Meta del mes',
    porLocal: 'Por local, hoy',
    porHora: 'Ventas por hora',
    cierres: 'Cierres de anoche',
    cierresVer: 'Ver los tres cierres',
    aprobar: 'Para aprobar',
    atencion: 'Requiere tu atención',
    atencionVer: 'Ver todas',
    ultimas: 'Últimas ventas',
    ultimasVer: 'Ver todas las ventas',
    sinVentas: 'Todavía no hay ventas hoy',
    sinVentasTexto: 'Cuando se registre la primera venta en cualquier local, aparece aquí.',
  },
  qr: {
    titulo: (numero: string) => `Llegó tu venta ${numero} desde el computador`,
    detalle: 'El código QR la trajo a este celular. Ya cuenta en las cifras de hoy.',
    varias: (n: number) => `Llegaron ${n} acciones desde el computador`,
    variasDetalle: 'El código QR las trajo a este celular. Ya cuentan en las cifras.',
    ver: 'Ver la venta',
    cerrar: 'Cerrar aviso',
    otraAncla: 'Este celular ya tenía otros datos de ejemplo',
    otraAnclaDetalle: 'El código venía de otra fecha de demostración y no se mezcló con lo que ya hay aquí.',
    invalido: 'No pudimos leer el código QR',
    invalidoDetalle: 'Pídele al computador que genere uno nuevo desde "Ver app del dueño".',
  },
  chip: {
    base: 'Cada celular y cada computador guardan sus propios datos de ejemplo.',
    qr: 'El código QR trae al celular lo último que hiciste en el computador.',
    adoptado: (n: number) => `Este celular recibió ${n === 1 ? 'la acción' : `las ${n} acciones`} del computador por el código QR.`,
    fusionado: (n: number) => `Este celular ya tenía datos de ejemplo y sumó ${n === 1 ? 'la acción' : `las ${n} acciones`} del código QR.`,
    otraAncla: 'El código QR venía de otra fecha de demostración, así que no se mezcló con lo que ya hay aquí.',
    invalido: 'No se pudo leer el código QR de este enlace.',
  },
  actualizar: {
    titulo: 'Hace un rato que no mirabas',
    texto: 'Las cifras son de la última vez que se prepararon los datos.',
    boton: 'Actualizar a la hora actual',
    listo: 'Datos al día',
  },
  ventas: {
    titulo: 'Ventas',
    periodos: { hoy: 'Hoy', semana: '7 días', mes: 'Mes' },
    vendido: { hoy: 'Vendido hoy', semana: 'Vendido en 7 días', mes: 'Vendido en el mes' },
    ticket: 'Ticket promedio',
    unidades: 'Unidades',
    numero: 'Ventas',
    margen: 'Margen bruto',
    descuentos: 'Descuentos',
    porLocal: 'Por local',
    lista: 'Ventas del periodo',
    verMas: 'Ver más ventas',
    vacio: 'Sin ventas en este periodo',
    vacioTexto: 'Cuando haya ventas en este rango, las ves aquí con su detalle.',
  },
  inventario: {
    titulo: 'Inventario',
    buscar: 'Buscar por nombre, referencia o código',
    stockBajo: 'Se está acabando',
    stockBajoVer: 'Ver todo lo que está bajo',
    sinResultados: 'No encontramos ese producto',
    sinResultadosTexto: 'Prueba con la referencia (HL-CAM-0142), el nombre o el código de barras.',
    sinBajo: 'Nada por debajo del mínimo',
    sinBajoTexto: 'Todas las referencias tienen existencias suficientes en este local.',
    enCamino: 'En camino',
    agotado: 'Agotado',
    porTalla: 'Existencias por talla',
    porLocal: 'Por local',
  },
  agenda: {
    titulo: 'Agenda',
    proximos: 'Próximos 14 días',
    vacio: 'No hay nada agendado',
    vacioTexto: 'Citas, llegadas de importaciones y pagos de los próximos días aparecen aquí.',
    ilustrativa: 'Ilustrativa',
    recordatorio: (min: number) =>
      min % 1440 === 0 ? `Aviso ${min / 1440 === 1 ? '1 día' : `${min / 1440} días`} antes` : min % 60 === 0 ? `Aviso ${min / 60 === 1 ? '1 hora' : `${min / 60} horas`} antes` : `Aviso ${min} min antes`,
  },
  cierres: {
    titulo: 'Cierres de caja',
    anoche: 'Anoche',
    sinCierre: 'Sin cierre',
    cuadro: 'Cuadró',
    revisado: 'Revisado',
    marcar: 'Marcar revisado',
    notaEtiqueta: 'Nota (opcional)',
    notaEjemplo: 'Hablé con Natalia; se descuenta del cambio de mañana',
    esperado: 'Esperado',
    contado: 'Contado',
    diferencia: 'Diferencia',
    arqueo: 'Arqueo por denominación',
    ciego: 'Arqueo ciego: quien cerró contó sin ver cuánto debía haber.',
    medios: 'Ventas por medio de pago',
    egresos: 'Egresos de caja',
    sinEgresos: 'Sin egresos en el día',
    composicion: 'Cómo se calcula el esperado',
    abierta: 'Esta caja todavía está abierta',
    abiertaTexto: 'Cuando la cierren, aquí ves el arqueo completo.',
  },
  aprobar: {
    titulo: 'Para aprobar',
    vacio: 'Todo al día',
    vacioTexto: 'No hay descuentos, traslados ni anulaciones esperando tu aprobación.',
    aprobar: 'Aprobar',
    rechazar: 'Rechazar',
    resueltas: 'Resueltas hace poco',
    notaRechazo: 'Motivo (opcional)',
  },
  mas: {
    titulo: 'Más',
    apariencia: 'Apariencia',
    modoClaro: 'Modo claro',
    modoClaroAyuda: 'La app es oscura por defecto. Cámbiala si te cansa la vista de día.',
    datos: 'Datos de este celular',
    instalar: 'Instala la app',
  },
  importaciones: {
    titulo: 'Importaciones',
    enCurso: 'En camino',
    recibidas: 'Ya recibidas',
    vacio: 'No hay importaciones en curso',
    vacioTexto: 'Cuando haya un pedido en camino desde China, ves su línea de tiempo aquí.',
  },
  nomina: {
    titulo: 'Nómina',
    vacio: 'Sin periodo por liquidar',
    vacioTexto: 'Cuando se abra el siguiente periodo, aquí ves lo que cuesta.',
    exoneracion: 'Con exoneración de aportes (salud, SENA e ICBF)',
  },
  pagos: {
    titulo: 'Pagos pendientes',
    porPagar: 'Por pagar',
    vencido: 'Vencido',
    porCobrar: 'Por cobrar',
    proximos: 'Próximos pagos',
    cobrar: 'Separados por cobrar',
    vacio: 'No hay pagos pendientes',
    vacioTexto: 'Cuando haya cuentas por pagar, las ves aquí con su fecha.',
  },
  alertas: {
    titulo: 'Alertas',
    vacio: 'Sin alertas por ahora',
    vacioTexto: 'Cuando algo requiera tu atención (inventario, caja, pagos, importaciones), aparece aquí.',
    descartar: 'Descartar',
    soloComputador: 'Se resuelve en el computador',
  },
  moneda: {
    titulo: 'Moneda',
    texto: 'Cambia en qué moneda ves todas las cifras de la app. Los datos siguen siendo en pesos.',
    tasa: 'Tasa de ejemplo',
  },
  abrirEnComputador: {
    titulo: 'Abre el sistema completo en tu computador',
    texto: 'El sistema completo está pensado para pantalla grande. Mándate el enlace y ábrelo allá.',
    compartir: 'Compartir enlace',
    copiar: 'Copiar enlace',
    copiado: 'Enlace copiado',
  },
  instalar: {
    titulo: 'Instala la app',
    instalada: 'Ya la tienes instalada',
    instaladaTexto: 'Se abre a pantalla completa desde tu pantalla de inicio.',
    ios: 'En Safari toca Compartir y luego "Agregar a inicio". Se abre a pantalla completa, como una app.',
    android: 'Instálala y se abre a pantalla completa desde tu pantalla de inicio.',
    androidManual: 'En Chrome toca el menú ⋮ y luego "Instalar app". Se abre a pantalla completa.',
    interno: 'Ábrela en Safari o Chrome para instalarla.',
    boton: 'Instalar app',
    copiar: 'Copiar enlace',
  },
  venta: {
    titulo: 'Detalle de la venta',
    cliente: 'Cliente',
    consumidorFinal: 'Consumidor final',
    vendedor: 'Vendedor',
    local: 'Local',
    medios: 'Cómo pagó',
    lineas: 'Prendas',
    total: 'Total',
    descuento: 'Descuento',
    anulada: 'Anulada',
    pendiente: 'Con saldo pendiente',
    noEncontrada: 'Esa venta ya no está en la lista',
  },
  comun: {
    cargando: 'Cargando',
    cerrar: 'Cerrar',
    atras: 'Atrás',
    todos: 'Todos los locales',
    errorTitulo: 'No pudimos mostrar esta pantalla',
    errorTexto: 'Vuelve a intentar. Tus datos están a salvo.',
    reintentar: 'Intentar de nuevo',
  },
} as const;
