/** Tipos del dominio (PLAN sección 6). */
export * from './comunes';
export * from './empresa';
export * from './sistema';
export * from './catalogo';
export * from './inventario';
export * from './ventas';
export * from './caja';
export * from './clientes';
export * from './personal';
export * from './nomina';
export * from './compras';
export * from './finanzas';
export * from './calendario';
export * from './facturacion';
export * from './mensajeria';
export * from './estado';
export * from './comandos';
export * from './eventos';
