import type {
  Categoria,
  Centavos,
  COP,
  CurvaTallas,
  Id,
  LineaProducto,
  MonedaExtranjera,
  TipoPrenda,
} from '@/dominio/tipos';

/**
 * Catálogo semilla (PLAN 5.4, 6.4, 7.13): 85 referencias con nombre en español, precios con IVA terminados
 * en 900 y solo tipos de prenda con ilustración (8.8). 883 variantes (talla × color), dentro del rango
 * 500–900 del PRD. El FOB está en la moneda de la fábrica y da los márgenes por categoría de 4.7 con el
 * costo aterrizado del generador (la Camisa Oxford entallada: US$ 11,40 → ≈ $ 71.850 puesta en bodega).
 */
export interface ReferenciaSeed {
  /** Id estable del producto. */
  id: Id;
  /** 'HL-CAM-0142' (formato HL-<CAT>-<NNNN>). */
  referencia: string;
  nombre: string;
  categoria: Categoria;
  linea: LineaProducto;
  tipoPrenda: TipoPrenda;
  curvaTallas: CurvaTallas;
  temporada: string;
  proveedorId: Id;
  material: string;
  descripcion: string;
  /** IVA incluido, terminado en 900. */
  precioVenta: COP;
  colorIds: Id[];
  /** FOB por unidad en la moneda de la fábrica. */
  fob: { moneda: MonedaExtranjera; centavos: Centavos };
  /** Peso relativo de demanda dentro de su categoría (P20: top 5 con pesos altos). */
  pesoDemanda: number;
  stockMinimo: number;
  publicadoEnTienda: boolean;
  destacado: boolean;
  etiquetas: string[];
  /** 'top5' (P20) · 'sin_movimiento' (P6: demanda 0 en los últimos 75 días). */
  narrativa: 'top5' | 'sin_movimiento' | null;
}

/** Código de categoría en la referencia (7.13). */
export const CODIGO_CATEGORIA: Record<Categoria, string> = {
  camisas: 'CAM',
  blazers: 'BLZ',
  pantalones: 'PAN',
  polos: 'POL',
  abrigos_chaquetas: 'ABR',
  punto: 'PUN',
  trajes: 'TRJ',
  calzado: 'CAL',
  accesorios: 'ACC',
};

export const NOMBRES_CATEGORIA: Record<Categoria, string> = {
  camisas: 'Camisas',
  blazers: 'Blazers y chalecos',
  pantalones: 'Pantalones',
  polos: 'Polos',
  abrigos_chaquetas: 'Abrigos y chaquetas',
  punto: 'Suéteres',
  trajes: 'Trajes',
  calzado: 'Calzado',
  accesorios: 'Accesorios',
};

export const NOMBRES_LINEA: Record<LineaProducto, string> = {
  sastreria: 'Sastrería',
  casual: 'Casual',
  sport: 'Sport',
};

/** Consecutivo inicial para las referencias que cree el usuario (7.13). */
export const CONSECUTIVO_PRODUCTO_INICIAL = 1000;

export const CATALOGO: ReferenciaSeed[] = [
  {
    id: 'pd_cam_0131',
    referencia: 'HL-CAM-0131',
    nombre: 'Camisa de popelina blanca',
    categoria: 'camisas',
    linea: 'sastreria',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: '100 % algodón popelina',
    descripcion: '100 % algodón popelina. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 189_900,
    colorIds: ['col_bla', 'col_azc'],
    fob: { moneda: 'USD', centavos: 960 },
    pesoDemanda: 1.0,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0132',
    referencia: 'HL-CAM-0132',
    nombre: 'Camisa de vestir cuello italiano',
    categoria: 'camisas',
    linea: 'sastreria',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Algodón de doble torsión',
    descripcion:
      'Algodón de doble torsión. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 209_900,
    colorIds: ['col_bla', 'col_azc'],
    fob: { moneda: 'USD', centavos: 1060 },
    pesoDemanda: 0.9,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0133',
    referencia: 'HL-CAM-0133',
    nombre: 'Camisa de vestir doble puño',
    categoria: 'camisas',
    linea: 'sastreria',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: '100 % algodón sarga fina',
    descripcion:
      '100 % algodón sarga fina. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 239_900,
    colorIds: ['col_bla', 'col_mfl'],
    fob: { moneda: 'USD', centavos: 1220 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0134',
    referencia: 'HL-CAM-0134',
    nombre: 'Camisa a rayas finas',
    categoria: 'camisas',
    linea: 'sastreria',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: '100 % algodón',
    descripcion: '100 % algodón. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 204_900,
    colorIds: ['col_raz', 'col_ram'],
    fob: { moneda: 'USD', centavos: 1040 },
    pesoDemanda: 0.8,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0135',
    referencia: 'HL-CAM-0135',
    nombre: 'Camisa de cuadros vichy',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: '100 % algodón',
    descripcion: '100 % algodón. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 179_900,
    colorIds: ['col_cuz', 'col_cuc'],
    fob: { moneda: 'USD', centavos: 910 },
    pesoDemanda: 0.8,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0136',
    referencia: 'HL-CAM-0136',
    nombre: 'Camisa de lino manga larga',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_huameng',
    material: '100 % lino',
    descripcion: '100 % lino. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 229_900,
    colorIds: ['col_bla', 'col_are', 'col_azc'],
    fob: { moneda: 'USD', centavos: 1160 },
    pesoDemanda: 0.9,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_cam_0137',
    referencia: 'HL-CAM-0137',
    nombre: 'Camisa de lino cuello mao',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_huameng',
    material: '100 % lino',
    descripcion: '100 % lino. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 214_900,
    colorIds: ['col_bla', 'col_oli'],
    fob: { moneda: 'USD', centavos: 1090 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_cam_0138',
    referencia: 'HL-CAM-0138',
    nombre: 'Camisa de franela a cuadros',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_huameng',
    material: 'Franela de algodón cepillado',
    descripcion:
      'Franela de algodón cepillado. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 194_900,
    colorIds: ['col_cuc', 'col_cuz'],
    fob: { moneda: 'USD', centavos: 990 },
    pesoDemanda: 0.7,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_cam_0139',
    referencia: 'HL-CAM-0139',
    nombre: 'Camisa de chambray',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Chambray de algodón',
    descripcion: 'Chambray de algodón. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 184_900,
    colorIds: ['col_azm'],
    fob: { moneda: 'USD', centavos: 940 },
    pesoDemanda: 0.7,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0140',
    referencia: 'HL-CAM-0140',
    nombre: 'Camisa Oxford regular',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: '100 % algodón Oxford',
    descripcion: '100 % algodón Oxford. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 207_900,
    colorIds: ['col_bla', 'col_azc', 'col_rsp'],
    fob: { moneda: 'USD', centavos: 1050 },
    pesoDemanda: 0.9,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0141',
    referencia: 'HL-CAM-0141',
    nombre: 'Camisa de algodón elástico',
    categoria: 'camisas',
    linea: 'sastreria',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Algodón con elastano',
    descripcion: 'Algodón con elastano. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 174_900,
    colorIds: ['col_bla', 'col_azc', 'col_neg'],
    fob: { moneda: 'USD', centavos: 890 },
    pesoDemanda: 1.0,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0142',
    referencia: 'HL-CAM-0142',
    nombre: 'Camisa Oxford entallada',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: '100 % algodón Oxford',
    descripcion: '100 % algodón Oxford. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 219_900,
    colorIds: ['col_azc', 'col_bla', 'col_azm'],
    fob: { moneda: 'USD', centavos: 1140 },
    pesoDemanda: 2.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: true,
    etiquetas: [],
    narrativa: 'top5',
  },
  {
    id: 'pd_cam_0143',
    referencia: 'HL-CAM-0143',
    nombre: 'Camisa de seda y algodón',
    categoria: 'camisas',
    linea: 'sastreria',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: '70 % algodón, 30 % seda',
    descripcion: '70 % algodón, 30 % seda. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 279_900,
    colorIds: ['col_bla', 'col_azn'],
    fob: { moneda: 'USD', centavos: 1420 },
    pesoDemanda: 0.4,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0144',
    referencia: 'HL-CAM-0144',
    nombre: 'Camisa estampada de microdiseño',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: '100 % algodón',
    descripcion: '100 % algodón. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 169_900,
    colorIds: ['col_azn', 'col_vin'],
    fob: { moneda: 'USD', centavos: 860 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cam_0145',
    referencia: 'HL-CAM-0145',
    nombre: 'Camisa de pana fina',
    categoria: 'camisas',
    linea: 'casual',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_huameng',
    material: 'Pana de algodón',
    descripcion: 'Pana de algodón. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 224_900,
    colorIds: ['col_cml', 'col_vbo'],
    fob: { moneda: 'USD', centavos: 1140 },
    pesoDemanda: 0.5,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_cam_0146',
    referencia: 'HL-CAM-0146',
    nombre: 'Camisa de denim ligero',
    categoria: 'camisas',
    linea: 'sport',
    tipoPrenda: 'camisa',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Denim de algodón de 6 onzas',
    descripcion:
      'Denim de algodón de 6 onzas. Manga larga, cuello con entretela suave y botones cosidos a mano.',
    precioVenta: 177_900,
    colorIds: ['col_azm', 'col_azn'],
    fob: { moneda: 'USD', centavos: 900 },
    pesoDemanda: 0.7,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pol_0201',
    referencia: 'HL-POL-0201',
    nombre: 'Polo piqué',
    categoria: 'polos',
    linea: 'casual',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Piqué de algodón',
    descripcion: 'Piqué de algodón. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 139_900,
    colorIds: ['col_azn', 'col_bla', 'col_neg', 'col_vbo'],
    fob: { moneda: 'USD', centavos: 630 },
    pesoDemanda: 2.4,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: true,
    etiquetas: [],
    narrativa: 'top5',
  },
  {
    id: 'pd_pol_0202',
    referencia: 'HL-POL-0202',
    nombre: 'Polo de algodón pima',
    categoria: 'polos',
    linea: 'casual',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Algodón pima',
    descripcion: 'Algodón pima. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 169_900,
    colorIds: ['col_bla', 'col_azn', 'col_are'],
    fob: { moneda: 'USD', centavos: 770 },
    pesoDemanda: 0.9,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pol_0203',
    referencia: 'HL-POL-0203',
    nombre: 'Polo de punto manga larga',
    categoria: 'polos',
    linea: 'casual',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_huameng',
    material: 'Punto de algodón',
    descripcion: 'Punto de algodón. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 186_900,
    colorIds: ['col_car', 'col_cml'],
    fob: { moneda: 'USD', centavos: 850 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pol_0204',
    referencia: 'HL-POL-0204',
    nombre: 'Polo a rayas náuticas',
    categoria: 'polos',
    linea: 'sport',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_huameng',
    material: 'Jersey de algodón',
    descripcion: 'Jersey de algodón. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 149_900,
    colorIds: ['col_ram'],
    fob: { moneda: 'USD', centavos: 680 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pol_0205',
    referencia: 'HL-POL-0205',
    nombre: 'Polo con cuello contraste',
    categoria: 'polos',
    linea: 'sport',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Piqué de algodón',
    descripcion: 'Piqué de algodón. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 144_900,
    colorIds: ['col_bla', 'col_azn'],
    fob: { moneda: 'USD', centavos: 660 },
    pesoDemanda: 0.7,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pol_0206',
    referencia: 'HL-POL-0206',
    nombre: 'Polo de lino',
    categoria: 'polos',
    linea: 'casual',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_huameng',
    material: 'Lino y algodón',
    descripcion: 'Lino y algodón. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 174_900,
    colorIds: ['col_are', 'col_azc'],
    fob: { moneda: 'USD', centavos: 790 },
    pesoDemanda: 0.5,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pol_0207',
    referencia: 'HL-POL-0207',
    nombre: 'Polo de jersey elástico',
    categoria: 'polos',
    linea: 'sport',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Algodón con elastano',
    descripcion: 'Algodón con elastano. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 129_900,
    colorIds: ['col_neg', 'col_grm', 'col_azm'],
    fob: { moneda: 'USD', centavos: 590 },
    pesoDemanda: 0.9,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pol_0208',
    referencia: 'HL-POL-0208',
    nombre: 'Polo de piqué manga larga',
    categoria: 'polos',
    linea: 'casual',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_huameng',
    material: 'Piqué de algodón',
    descripcion: 'Piqué de algodón. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 159_900,
    colorIds: ['col_azn', 'col_vin'],
    fob: { moneda: 'USD', centavos: 720 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pol_0209',
    referencia: 'HL-POL-0209',
    nombre: 'Polo de punto con cremallera',
    categoria: 'polos',
    linea: 'casual',
    tipoPrenda: 'polo',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_huameng',
    material: 'Punto de algodón',
    descripcion: 'Punto de algodón. Cuello y puños de punto, tapeta de tres botones.',
    precioVenta: 182_900,
    colorIds: ['col_car', 'col_azn'],
    fob: { moneda: 'USD', centavos: 830 },
    pesoDemanda: 0.5,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pan_0301',
    referencia: 'HL-PAN-0301',
    nombre: 'Pantalón de vestir de lana fría',
    categoria: 'pantalones',
    linea: 'sastreria',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: 'Lana fría',
    descripcion: 'Lana fría. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 289_900,
    colorIds: ['col_azn', 'col_car'],
    fob: { moneda: 'CNY', centavos: 11140 },
    pesoDemanda: 1.0,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pan_0302',
    referencia: 'HL-PAN-0302',
    nombre: 'Pantalón chino de algodón regular',
    categoria: 'pantalones',
    linea: 'casual',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: '100 % algodón',
    descripcion: '100 % algodón. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 179_900,
    colorIds: ['col_are', 'col_azn'],
    fob: { moneda: 'CNY', centavos: 6920 },
    pesoDemanda: 1.0,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pan_0303',
    referencia: 'HL-PAN-0303',
    nombre: 'Jean de corte recto',
    categoria: 'pantalones',
    linea: 'casual',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: 'Denim de algodón',
    descripcion: 'Denim de algodón. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 214_900,
    colorIds: ['col_azn', 'col_azm'],
    fob: { moneda: 'CNY', centavos: 8260 },
    pesoDemanda: 1.0,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pan_0304',
    referencia: 'HL-PAN-0304',
    nombre: 'Jean entallado',
    categoria: 'pantalones',
    linea: 'casual',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: 'Denim con elastano',
    descripcion: 'Denim con elastano. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 229_900,
    colorIds: ['col_azn', 'col_neg'],
    fob: { moneda: 'CNY', centavos: 8840 },
    pesoDemanda: 0.9,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pan_0305',
    referencia: 'HL-PAN-0305',
    nombre: 'Pantalón chino elástico',
    categoria: 'pantalones',
    linea: 'casual',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: 'Algodón con elastano',
    descripcion: 'Algodón con elastano. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 199_900,
    colorIds: ['col_are', 'col_azn', 'col_cml', 'col_grc'],
    fob: { moneda: 'CNY', centavos: 7680 },
    pesoDemanda: 2.5,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: true,
    etiquetas: [],
    narrativa: 'top5',
  },
  {
    id: 'pd_pan_0306',
    referencia: 'HL-PAN-0306',
    nombre: 'Pantalón de pana',
    categoria: 'pantalones',
    linea: 'casual',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_yuefeng',
    material: 'Pana de algodón',
    descripcion: 'Pana de algodón. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 239_900,
    colorIds: ['col_caf', 'col_vbo'],
    fob: { moneda: 'CNY', centavos: 9220 },
    pesoDemanda: 0.5,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pan_0307',
    referencia: 'HL-PAN-0307',
    nombre: 'Pantalón de franela gris',
    categoria: 'pantalones',
    linea: 'sastreria',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_yuefeng',
    material: 'Franela de lana',
    descripcion: 'Franela de lana. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 269_900,
    colorIds: ['col_grm', 'col_car'],
    fob: { moneda: 'CNY', centavos: 10380 },
    pesoDemanda: 0.5,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pan_0308',
    referencia: 'HL-PAN-0308',
    nombre: 'Pantalón de lino',
    categoria: 'pantalones',
    linea: 'casual',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_yuefeng',
    material: '100 % lino',
    descripcion: '100 % lino. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 209_900,
    colorIds: ['col_are', 'col_bla'],
    fob: { moneda: 'CNY', centavos: 8070 },
    pesoDemanda: 0.5,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pan_0309',
    referencia: 'HL-PAN-0309',
    nombre: 'Pantalón cargo ligero',
    categoria: 'pantalones',
    linea: 'sport',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: 'Algodón ripstop',
    descripcion: 'Algodón ripstop. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 189_900,
    colorIds: ['col_oli', 'col_are'],
    fob: { moneda: 'CNY', centavos: 7300 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pan_0310',
    referencia: 'HL-PAN-0310',
    nombre: 'Pantalón jogger de algodón',
    categoria: 'pantalones',
    linea: 'sport',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: 'Felpa de algodón',
    descripcion: 'Felpa de algodón. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 159_900,
    colorIds: ['col_neg', 'col_car'],
    fob: { moneda: 'CNY', centavos: 6150 },
    pesoDemanda: 0.7,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pan_0311',
    referencia: 'HL-PAN-0311',
    nombre: 'Pantalón de sastre a cuadros',
    categoria: 'pantalones',
    linea: 'sastreria',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: 'Lana y viscosa',
    descripcion: 'Lana y viscosa. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 299_900,
    colorIds: ['col_cuz'],
    fob: { moneda: 'CNY', centavos: 11530 },
    pesoDemanda: 0.4,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pan_0312',
    referencia: 'HL-PAN-0312',
    nombre: 'Pantalón de gabardina',
    categoria: 'pantalones',
    linea: 'casual',
    tipoPrenda: 'pantalon',
    curvaTallas: 'pantalon',
    temporada: 'Colección permanente',
    proveedorId: 'pr_yuefeng',
    material: 'Gabardina de algodón',
    descripcion: 'Gabardina de algodón. Pretina con trabillas, bolsillos sesgados y bajo sin dobladillo.',
    precioVenta: 194_900,
    colorIds: ['col_azn', 'col_cml'],
    fob: { moneda: 'CNY', centavos: 7490 },
    pesoDemanda: 0.8,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_blz_0401',
    referencia: 'HL-BLZ-0401',
    nombre: 'Blazer de lana fría',
    categoria: 'blazers',
    linea: 'sastreria',
    tipoPrenda: 'blazer',
    curvaTallas: 'sastreria',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Lana fría',
    descripcion: 'Lana fría. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 789_900,
    colorIds: ['col_azn', 'col_car'],
    fob: { moneda: 'USD', centavos: 4840 },
    pesoDemanda: 2.4,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: true,
    etiquetas: [],
    narrativa: 'top5',
  },
  {
    id: 'pd_blz_0402',
    referencia: 'HL-BLZ-0402',
    nombre: 'Blazer de lino',
    categoria: 'blazers',
    linea: 'casual',
    tipoPrenda: 'blazer',
    curvaTallas: 'sastreria',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_weiye',
    material: '100 % lino',
    descripcion: '100 % lino. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 649_900,
    colorIds: ['col_are', 'col_azm'],
    fob: { moneda: 'USD', centavos: 3990 },
    pesoDemanda: 0.6,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_blz_0403',
    referencia: 'HL-BLZ-0403',
    nombre: 'Blazer cruzado mostaza',
    categoria: 'blazers',
    linea: 'sastreria',
    tipoPrenda: 'blazer',
    curvaTallas: 'sastreria',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Lana y cachemira',
    descripcion: 'Lana y cachemira. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 829_900,
    colorIds: ['col_mos'],
    fob: { moneda: 'USD', centavos: 5090 },
    pesoDemanda: 0.3,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: 'sin_movimiento',
  },
  {
    id: 'pd_blz_0404',
    referencia: 'HL-BLZ-0404',
    nombre: 'Blazer de pana',
    categoria: 'blazers',
    linea: 'casual',
    tipoPrenda: 'blazer',
    curvaTallas: 'sastreria',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_weiye',
    material: 'Pana de algodón',
    descripcion: 'Pana de algodón. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 699_900,
    colorIds: ['col_caf', 'col_vbo'],
    fob: { moneda: 'USD', centavos: 4290 },
    pesoDemanda: 0.5,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_blz_0405',
    referencia: 'HL-BLZ-0405',
    nombre: 'Blazer de punto',
    categoria: 'blazers',
    linea: 'casual',
    tipoPrenda: 'blazer',
    curvaTallas: 'sastreria',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Punto de lana',
    descripcion: 'Punto de lana. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 589_900,
    colorIds: ['col_azn', 'col_grm'],
    fob: { moneda: 'USD', centavos: 3620 },
    pesoDemanda: 0.7,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_blz_0406',
    referencia: 'HL-BLZ-0406',
    nombre: 'Blazer desestructurado de algodón',
    categoria: 'blazers',
    linea: 'casual',
    tipoPrenda: 'blazer',
    curvaTallas: 'sastreria',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Algodón y lino',
    descripcion: 'Algodón y lino. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 559_900,
    colorIds: ['col_azm', 'col_are'],
    fob: { moneda: 'USD', centavos: 3430 },
    pesoDemanda: 0.7,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_blz_0407',
    referencia: 'HL-BLZ-0407',
    nombre: 'Chaleco de lino beige',
    categoria: 'blazers',
    linea: 'casual',
    tipoPrenda: 'chaleco',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_weiye',
    material: '100 % lino',
    descripcion: '100 % lino. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 279_900,
    colorIds: ['col_are'],
    fob: { moneda: 'USD', centavos: 1720 },
    pesoDemanda: 0.3,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: 'sin_movimiento',
  },
  {
    id: 'pd_blz_0408',
    referencia: 'HL-BLZ-0408',
    nombre: 'Chaleco de lana gris',
    categoria: 'blazers',
    linea: 'sastreria',
    tipoPrenda: 'chaleco',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Lana fría',
    descripcion: 'Lana fría. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 319_900,
    colorIds: ['col_grm', 'col_car'],
    fob: { moneda: 'USD', centavos: 1960 },
    pesoDemanda: 0.5,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_blz_0409',
    referencia: 'HL-BLZ-0409',
    nombre: 'Chaleco de traje azul marino',
    categoria: 'blazers',
    linea: 'sastreria',
    tipoPrenda: 'chaleco',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Lana fría',
    descripcion: 'Lana fría. Hombro natural, forro parcial y dos aberturas atrás.',
    precioVenta: 299_900,
    colorIds: ['col_azn'],
    fob: { moneda: 'USD', centavos: 1840 },
    pesoDemanda: 0.6,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_trj_0501',
    referencia: 'HL-TRJ-0501',
    nombre: 'Traje de lana fría azul marino',
    categoria: 'trajes',
    linea: 'sastreria',
    tipoPrenda: 'traje',
    curvaTallas: 'sastreria',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Lana fría Super 110',
    descripcion:
      'Lana fría Super 110. Saco de dos botones y pantalón sin pinzas, con bajo sin terminar para ajustar.',
    precioVenta: 1_489_900,
    colorIds: ['col_azn'],
    fob: { moneda: 'USD', centavos: 9540 },
    pesoDemanda: 1.4,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: true,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_trj_0502',
    referencia: 'HL-TRJ-0502',
    nombre: 'Traje gris carbón',
    categoria: 'trajes',
    linea: 'sastreria',
    tipoPrenda: 'traje',
    curvaTallas: 'sastreria',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Lana fría',
    descripcion: 'Lana fría. Saco de dos botones y pantalón sin pinzas, con bajo sin terminar para ajustar.',
    precioVenta: 1_389_900,
    colorIds: ['col_car'],
    fob: { moneda: 'USD', centavos: 8900 },
    pesoDemanda: 1.0,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_trj_0503',
    referencia: 'HL-TRJ-0503',
    nombre: 'Traje de lino',
    categoria: 'trajes',
    linea: 'sastreria',
    tipoPrenda: 'traje',
    curvaTallas: 'sastreria',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_weiye',
    material: '100 % lino',
    descripcion: '100 % lino. Saco de dos botones y pantalón sin pinzas, con bajo sin terminar para ajustar.',
    precioVenta: 1_189_900,
    colorIds: ['col_are', 'col_azm'],
    fob: { moneda: 'USD', centavos: 7620 },
    pesoDemanda: 0.5,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_trj_0504',
    referencia: 'HL-TRJ-0504',
    nombre: 'Traje a rayas diplomáticas',
    categoria: 'trajes',
    linea: 'sastreria',
    tipoPrenda: 'traje',
    curvaTallas: 'sastreria',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Lana fría',
    descripcion: 'Lana fría. Saco de dos botones y pantalón sin pinzas, con bajo sin terminar para ajustar.',
    precioVenta: 1_589_900,
    colorIds: ['col_ram'],
    fob: { moneda: 'USD', centavos: 10180 },
    pesoDemanda: 0.5,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_trj_0505',
    referencia: 'HL-TRJ-0505',
    nombre: 'Traje de tres piezas',
    categoria: 'trajes',
    linea: 'sastreria',
    tipoPrenda: 'traje',
    curvaTallas: 'sastreria',
    temporada: 'Colección permanente',
    proveedorId: 'pr_weiye',
    material: 'Lana fría',
    descripcion: 'Lana fría. Saco de dos botones y pantalón sin pinzas, con bajo sin terminar para ajustar.',
    precioVenta: 1_789_900,
    colorIds: ['col_grm', 'col_azn'],
    fob: { moneda: 'USD', centavos: 11460 },
    pesoDemanda: 0.5,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_trj_0506',
    referencia: 'HL-TRJ-0506',
    nombre: 'Traje de lana texturizada',
    categoria: 'trajes',
    linea: 'sastreria',
    tipoPrenda: 'traje',
    curvaTallas: 'sastreria',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_weiye',
    material: 'Lana texturizada',
    descripcion:
      'Lana texturizada. Saco de dos botones y pantalón sin pinzas, con bajo sin terminar para ajustar.',
    precioVenta: 1_449_900,
    colorIds: ['col_caf', 'col_grm'],
    fob: { moneda: 'USD', centavos: 9280 },
    pesoDemanda: 0.4,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pun_0601',
    referencia: 'HL-PUN-0601',
    nombre: 'Suéter de merino cuello redondo',
    categoria: 'punto',
    linea: 'casual',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: '100 % lana merino',
    descripcion: '100 % lana merino. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 259_900,
    colorIds: ['col_azn', 'col_grm', 'col_cml', 'col_are', 'col_vin'],
    fob: { moneda: 'USD', centavos: 1460 },
    pesoDemanda: 2.2,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: true,
    etiquetas: [],
    narrativa: 'top5',
  },
  {
    id: 'pd_pun_0602',
    referencia: 'HL-PUN-0602',
    nombre: 'Suéter de merino cuello en V',
    categoria: 'punto',
    linea: 'casual',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: '100 % lana merino',
    descripcion: '100 % lana merino. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 249_900,
    colorIds: ['col_azn', 'col_car', 'col_vbo'],
    fob: { moneda: 'USD', centavos: 1400 },
    pesoDemanda: 1.0,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pun_0603',
    referencia: 'HL-PUN-0603',
    nombre: 'Suéter de cachemira',
    categoria: 'punto',
    linea: 'casual',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_lanxin',
    material: '100 % cachemira',
    descripcion: '100 % cachemira. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 489_900,
    colorIds: ['col_cml', 'col_grc'],
    fob: { moneda: 'USD', centavos: 2740 },
    pesoDemanda: 0.4,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pun_0604',
    referencia: 'HL-PUN-0604',
    nombre: 'Cárdigan de lana',
    categoria: 'punto',
    linea: 'casual',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_lanxin',
    material: 'Lana y alpaca',
    descripcion: 'Lana y alpaca. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 319_900,
    colorIds: ['col_car', 'col_cml'],
    fob: { moneda: 'USD', centavos: 1790 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pun_0605',
    referencia: 'HL-PUN-0605',
    nombre: 'Suéter de cuello alto',
    categoria: 'punto',
    linea: 'casual',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_lanxin',
    material: 'Lana merino',
    descripcion: 'Lana merino. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 279_900,
    colorIds: ['col_neg', 'col_mfl', 'col_azn'],
    fob: { moneda: 'USD', centavos: 1570 },
    pesoDemanda: 0.7,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pun_0606',
    referencia: 'HL-PUN-0606',
    nombre: 'Suéter de algodón trenzado',
    categoria: 'punto',
    linea: 'casual',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: '100 % algodón',
    descripcion: '100 % algodón. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 229_900,
    colorIds: ['col_mfl', 'col_azn'],
    fob: { moneda: 'USD', centavos: 1290 },
    pesoDemanda: 0.7,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pun_0607',
    referencia: 'HL-PUN-0607',
    nombre: 'Suéter de medio cierre',
    categoria: 'punto',
    linea: 'sport',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: 'Lana merino',
    descripcion: 'Lana merino. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 269_900,
    colorIds: ['col_grm', 'col_azn'],
    fob: { moneda: 'USD', centavos: 1510 },
    pesoDemanda: 0.7,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_pun_0608',
    referencia: 'HL-PUN-0608',
    nombre: 'Suéter de lana jaspeado',
    categoria: 'punto',
    linea: 'casual',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_lanxin',
    material: 'Lana jaspeada',
    descripcion: 'Lana jaspeada. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 239_900,
    colorIds: ['col_grc', 'col_caf'],
    fob: { moneda: 'USD', centavos: 1340 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_pun_0609',
    referencia: 'HL-PUN-0609',
    nombre: 'Suéter liviano de algodón',
    categoria: 'punto',
    linea: 'casual',
    tipoPrenda: 'sweater',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-I',
    proveedorId: 'pr_lanxin',
    material: '100 % algodón',
    descripcion: '100 % algodón. Tejido fino que no pica; puños y bajo en resorte.',
    precioVenta: 189_900,
    colorIds: ['col_are', 'col_azc', 'col_bla'],
    fob: { moneda: 'USD', centavos: 1060 },
    pesoDemanda: 0.8,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_abr_0701',
    referencia: 'HL-ABR-0701',
    nombre: 'Abrigo de paño',
    categoria: 'abrigos_chaquetas',
    linea: 'sastreria',
    tipoPrenda: 'abrigo',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_lanxin',
    material: 'Paño de lana',
    descripcion: 'Paño de lana. Para las mañanas frías de Bogotá; bolsillos interiores.',
    precioVenta: 989_900,
    colorIds: ['col_cml', 'col_car', 'col_azn'],
    fob: { moneda: 'USD', centavos: 5940 },
    pesoDemanda: 0.7,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: true,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_abr_0702',
    referencia: 'HL-ABR-0702',
    nombre: 'Gabardina clásica',
    categoria: 'abrigos_chaquetas',
    linea: 'sastreria',
    tipoPrenda: 'abrigo',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: 'Gabardina de algodón',
    descripcion: 'Gabardina de algodón. Para las mañanas frías de Bogotá; bolsillos interiores.',
    precioVenta: 849_900,
    colorIds: ['col_are', 'col_azn'],
    fob: { moneda: 'USD', centavos: 5100 },
    pesoDemanda: 0.6,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_abr_0703',
    referencia: 'HL-ABR-0703',
    nombre: 'Abrigo cruzado de lana',
    categoria: 'abrigos_chaquetas',
    linea: 'sastreria',
    tipoPrenda: 'abrigo',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_lanxin',
    material: 'Lana y cachemira',
    descripcion: 'Lana y cachemira. Para las mañanas frías de Bogotá; bolsillos interiores.',
    precioVenta: 1_089_900,
    colorIds: ['col_grm', 'col_neg'],
    fob: { moneda: 'USD', centavos: 6540 },
    pesoDemanda: 0.4,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_abr_0704',
    referencia: 'HL-ABR-0704',
    nombre: 'Chaqueta acolchada ligera',
    categoria: 'abrigos_chaquetas',
    linea: 'sport',
    tipoPrenda: 'chaqueta',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: 'Nailon con relleno sintético',
    descripcion: 'Nailon con relleno sintético. Para las mañanas frías de Bogotá; bolsillos interiores.',
    precioVenta: 489_900,
    colorIds: ['col_azn', 'col_oli', 'col_neg'],
    fob: { moneda: 'USD', centavos: 2940 },
    pesoDemanda: 0.8,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_abr_0705',
    referencia: 'HL-ABR-0705',
    nombre: 'Chaqueta de gamuza',
    categoria: 'abrigos_chaquetas',
    linea: 'casual',
    tipoPrenda: 'chaqueta',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_lanxin',
    material: 'Gamuza',
    descripcion: 'Gamuza. Para las mañanas frías de Bogotá; bolsillos interiores.',
    precioVenta: 899_900,
    colorIds: ['col_caf', 'col_cml'],
    fob: { moneda: 'USD', centavos: 5400 },
    pesoDemanda: 0.4,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_abr_0706',
    referencia: 'HL-ABR-0706',
    nombre: 'Chaqueta de algodón encerado',
    categoria: 'abrigos_chaquetas',
    linea: 'casual',
    tipoPrenda: 'chaqueta',
    curvaTallas: 'superior',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: 'Algodón encerado',
    descripcion: 'Algodón encerado. Para las mañanas frías de Bogotá; bolsillos interiores.',
    precioVenta: 629_900,
    colorIds: ['col_oli', 'col_azn'],
    fob: { moneda: 'USD', centavos: 3780 },
    pesoDemanda: 0.5,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_abr_0707',
    referencia: 'HL-ABR-0707',
    nombre: 'Chaqueta bomber de lana',
    categoria: 'abrigos_chaquetas',
    linea: 'casual',
    tipoPrenda: 'chaqueta',
    curvaTallas: 'superior',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_lanxin',
    material: 'Lana',
    descripcion: 'Lana. Para las mañanas frías de Bogotá; bolsillos interiores.',
    precioVenta: 559_900,
    colorIds: ['col_azn', 'col_car'],
    fob: { moneda: 'USD', centavos: 3360 },
    pesoDemanda: 0.5,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_cal_0801',
    referencia: 'HL-CAL-0801',
    nombre: 'Mocasín de gamuza café',
    categoria: 'calzado',
    linea: 'casual',
    tipoPrenda: 'zapato',
    curvaTallas: 'calzado',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Gamuza',
    descripcion: 'Gamuza. Suela de cuero con taco de caucho y plantilla acolchada.',
    precioVenta: 389_900,
    colorIds: ['col_caf'],
    fob: { moneda: 'CNY', centavos: 19490 },
    pesoDemanda: 0.3,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: 'sin_movimiento',
  },
  {
    id: 'pd_cal_0802',
    referencia: 'HL-CAL-0802',
    nombre: 'Zapato Oxford de cuero vinotinto',
    categoria: 'calzado',
    linea: 'sastreria',
    tipoPrenda: 'zapato',
    curvaTallas: 'calzado',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero de becerro',
    descripcion: 'Cuero de becerro. Suela de cuero con taco de caucho y plantilla acolchada.',
    precioVenta: 459_900,
    colorIds: ['col_vin'],
    fob: { moneda: 'CNY', centavos: 22980 },
    pesoDemanda: 0.3,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: 'sin_movimiento',
  },
  {
    id: 'pd_cal_0803',
    referencia: 'HL-CAL-0803',
    nombre: 'Zapato Oxford de cuero negro',
    categoria: 'calzado',
    linea: 'sastreria',
    tipoPrenda: 'zapato',
    curvaTallas: 'calzado',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero de becerro',
    descripcion: 'Cuero de becerro. Suela de cuero con taco de caucho y plantilla acolchada.',
    precioVenta: 449_900,
    colorIds: ['col_neg'],
    fob: { moneda: 'CNY', centavos: 22480 },
    pesoDemanda: 1.0,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: true,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cal_0804',
    referencia: 'HL-CAL-0804',
    nombre: 'Mocasín de cuero con antifaz',
    categoria: 'calzado',
    linea: 'casual',
    tipoPrenda: 'zapato',
    curvaTallas: 'calzado',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero',
    descripcion: 'Cuero. Suela de cuero con taco de caucho y plantilla acolchada.',
    precioVenta: 419_900,
    colorIds: ['col_caf'],
    fob: { moneda: 'CNY', centavos: 20980 },
    pesoDemanda: 0.8,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cal_0805',
    referencia: 'HL-CAL-0805',
    nombre: 'Botín Chelsea de gamuza',
    categoria: 'calzado',
    linea: 'casual',
    tipoPrenda: 'zapato',
    curvaTallas: 'calzado',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_ruifeng',
    material: 'Gamuza',
    descripcion: 'Gamuza. Suela de cuero con taco de caucho y plantilla acolchada.',
    precioVenta: 479_900,
    colorIds: ['col_are', 'col_caf'],
    fob: { moneda: 'CNY', centavos: 23980 },
    pesoDemanda: 0.7,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_cal_0806',
    referencia: 'HL-CAL-0806',
    nombre: 'Botín de cuero con cordones',
    categoria: 'calzado',
    linea: 'casual',
    tipoPrenda: 'zapato',
    curvaTallas: 'calzado',
    temporada: 'Temporada 2026-II',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero engrasado',
    descripcion: 'Cuero engrasado. Suela de cuero con taco de caucho y plantilla acolchada.',
    precioVenta: 499_900,
    colorIds: ['col_caf'],
    fob: { moneda: 'CNY', centavos: 24980 },
    pesoDemanda: 0.6,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: ['temporada'],
    narrativa: null,
  },
  {
    id: 'pd_cal_0807',
    referencia: 'HL-CAL-0807',
    nombre: 'Zapato derby de cuero',
    categoria: 'calzado',
    linea: 'sastreria',
    tipoPrenda: 'zapato',
    curvaTallas: 'calzado',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero',
    descripcion: 'Cuero. Suela de cuero con taco de caucho y plantilla acolchada.',
    precioVenta: 429_900,
    colorIds: ['col_neg'],
    fob: { moneda: 'CNY', centavos: 21480 },
    pesoDemanda: 0.8,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_cal_0808',
    referencia: 'HL-CAL-0808',
    nombre: 'Mocasín de conducir',
    categoria: 'calzado',
    linea: 'casual',
    tipoPrenda: 'zapato',
    curvaTallas: 'calzado',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Gamuza',
    descripcion: 'Gamuza. Suela de cuero con taco de caucho y plantilla acolchada.',
    precioVenta: 349_900,
    colorIds: ['col_azn', 'col_cml'],
    fob: { moneda: 'CNY', centavos: 17490 },
    pesoDemanda: 0.6,
    stockMinimo: 1,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_acc_0901',
    referencia: 'HL-ACC-0901',
    nombre: 'Corbata de seda lisa',
    categoria: 'accesorios',
    linea: 'sastreria',
    tipoPrenda: 'corbata',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: '100 % seda',
    descripcion: '100 % seda. Terminación a mano; viene en caja de regalo.',
    precioVenta: 129_900,
    colorIds: ['col_azn', 'col_vin', 'col_vbo', 'col_grm'],
    fob: { moneda: 'USD', centavos: 610 },
    pesoDemanda: 1.4,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_acc_0902',
    referencia: 'HL-ACC-0902',
    nombre: 'Corbata de seda estampada de cachemir',
    categoria: 'accesorios',
    linea: 'sastreria',
    tipoPrenda: 'corbata',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: '100 % seda',
    descripcion: '100 % seda. Terminación a mano; viene en caja de regalo.',
    precioVenta: 139_900,
    colorIds: ['col_vin'],
    fob: { moneda: 'USD', centavos: 650 },
    pesoDemanda: 0.3,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: 'sin_movimiento',
  },
  {
    id: 'pd_acc_0903',
    referencia: 'HL-ACC-0903',
    nombre: 'Corbata de punto',
    categoria: 'accesorios',
    linea: 'casual',
    tipoPrenda: 'corbata',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: 'Punto de seda',
    descripcion: 'Punto de seda. Terminación a mano; viene en caja de regalo.',
    precioVenta: 119_900,
    colorIds: ['col_azn', 'col_neg'],
    fob: { moneda: 'USD', centavos: 560 },
    pesoDemanda: 0.8,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_acc_0904',
    referencia: 'HL-ACC-0904',
    nombre: 'Corbata a rayas',
    categoria: 'accesorios',
    linea: 'sastreria',
    tipoPrenda: 'corbata',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_lanxin',
    material: '100 % seda',
    descripcion: '100 % seda. Terminación a mano; viene en caja de regalo.',
    precioVenta: 124_900,
    colorIds: ['col_ram'],
    fob: { moneda: 'USD', centavos: 580 },
    pesoDemanda: 0.8,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_acc_0905',
    referencia: 'HL-ACC-0905',
    nombre: 'Cinturón de cuero liso',
    categoria: 'accesorios',
    linea: 'sastreria',
    tipoPrenda: 'cinturon',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero',
    descripcion: 'Cuero. Terminación a mano; viene en caja de regalo.',
    precioVenta: 149_900,
    colorIds: ['col_neg', 'col_caf'],
    fob: { moneda: 'CNY', centavos: 5040 },
    pesoDemanda: 1.2,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_acc_0906',
    referencia: 'HL-ACC-0906',
    nombre: 'Cinturón de cuero trenzado',
    categoria: 'accesorios',
    linea: 'casual',
    tipoPrenda: 'cinturon',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero trenzado',
    descripcion: 'Cuero trenzado. Terminación a mano; viene en caja de regalo.',
    precioVenta: 134_900,
    colorIds: ['col_caf', 'col_cml'],
    fob: { moneda: 'CNY', centavos: 4540 },
    pesoDemanda: 0.8,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_acc_0907',
    referencia: 'HL-ACC-0907',
    nombre: 'Cinturón reversible',
    categoria: 'accesorios',
    linea: 'sastreria',
    tipoPrenda: 'cinturon',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero',
    descripcion: 'Cuero. Terminación a mano; viene en caja de regalo.',
    precioVenta: 159_900,
    colorIds: ['col_neg'],
    fob: { moneda: 'CNY', centavos: 5380 },
    pesoDemanda: 0.6,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_acc_0908',
    referencia: 'HL-ACC-0908',
    nombre: 'Billetera de cuero',
    categoria: 'accesorios',
    linea: 'casual',
    tipoPrenda: 'billetera',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero',
    descripcion: 'Cuero. Terminación a mano; viene en caja de regalo.',
    precioVenta: 169_900,
    colorIds: ['col_neg', 'col_caf'],
    fob: { moneda: 'CNY', centavos: 5710 },
    pesoDemanda: 1.0,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
  {
    id: 'pd_acc_0909',
    referencia: 'HL-ACC-0909',
    nombre: 'Billetera tarjetero',
    categoria: 'accesorios',
    linea: 'casual',
    tipoPrenda: 'billetera',
    curvaTallas: 'unica',
    temporada: 'Colección permanente',
    proveedorId: 'pr_ruifeng',
    material: 'Cuero',
    descripcion: 'Cuero. Terminación a mano; viene en caja de regalo.',
    precioVenta: 99_900,
    colorIds: ['col_neg', 'col_cml', 'col_azn'],
    fob: { moneda: 'CNY', centavos: 3360 },
    pesoDemanda: 0.9,
    stockMinimo: 2,
    publicadoEnTienda: true,
    destacado: false,
    etiquetas: [],
    narrativa: null,
  },
];
