import type { DatosGastoRecurrente, Id } from '@/dominio/tipos';

/**
 * Gastos fijos y recurrentes por local (PLAN 7.10). Los arriendos vencen el día 5 (CxP emitida el día 1).
 * Valores con IVA donde aplica. `desde` se fija en el mes de inicio de la ventana (estadoInicial).
 */
type Recurrente = Omit<DatosGastoRecurrente, 'desde' | 'hasta' | 'activo'> & { id: Id };

export const GASTOS_RECURRENTES: Recurrente[] = [
  {
    id: 'gr_arriendo_p93',
    nombre: 'Arriendo Parque 93',
    categoria: 'arriendo',
    localId: 'p93',
    valor: 18_500_000,
    iva: 0,
    diaDelMes: 1,
    proveedorId: 'pr_arr_p93',
    formaPago: 'cuenta_por_pagar',
    diasPlazo: 4,
    cuentaId: null,
  },
  {
    id: 'gr_arriendo_usq',
    nombre: 'Arriendo Usaquén',
    categoria: 'arriendo',
    localId: 'usq',
    valor: 9_800_000,
    iva: 0,
    diaDelMes: 1,
    proveedorId: 'pr_arr_usq',
    formaPago: 'cuenta_por_pagar',
    diasPlazo: 4,
    cuentaId: null,
  },
  {
    id: 'gr_arriendo_zr',
    nombre: 'Arriendo y administración Zona Rosa',
    categoria: 'arriendo',
    localId: 'zr',
    valor: 14_200_000,
    iva: 0,
    diaDelMes: 1,
    proveedorId: 'pr_arr_zr',
    formaPago: 'cuenta_por_pagar',
    diasPlazo: 4,
    cuentaId: null,
  },
  {
    id: 'gr_arriendo_bod',
    nombre: 'Arriendo bodega Puente Aranda',
    categoria: 'arriendo',
    localId: null,
    valor: 6_500_000,
    iva: 0,
    diaDelMes: 1,
    proveedorId: null,
    formaPago: 'cuenta_por_pagar',
    diasPlazo: 4,
    cuentaId: null,
  },
  {
    id: 'gr_energia_p93',
    nombre: 'Energía Parque 93',
    categoria: 'servicios',
    localId: 'p93',
    valor: 1_480_000,
    iva: 0,
    diaDelMes: 18,
    proveedorId: null,
    formaPago: 'debito_automatico',
    diasPlazo: 0,
    cuentaId: 'cta_corriente',
  },
  {
    id: 'gr_energia_usq',
    nombre: 'Energía Usaquén',
    categoria: 'servicios',
    localId: 'usq',
    valor: 920_000,
    iva: 0,
    diaDelMes: 18,
    proveedorId: null,
    formaPago: 'debito_automatico',
    diasPlazo: 0,
    cuentaId: 'cta_corriente',
  },
  {
    id: 'gr_energia_zr',
    nombre: 'Energía Zona Rosa',
    categoria: 'servicios',
    localId: 'zr',
    valor: 1_150_000,
    iva: 0,
    diaDelMes: 18,
    proveedorId: null,
    formaPago: 'debito_automatico',
    diasPlazo: 0,
    cuentaId: 'cta_corriente',
  },
  {
    id: 'gr_agua_aseo',
    nombre: 'Agua y aseo de los locales',
    categoria: 'servicios',
    localId: null,
    valor: 640_000,
    iva: 0,
    diaDelMes: 20,
    proveedorId: null,
    formaPago: 'debito_automatico',
    diasPlazo: 0,
    cuentaId: 'cta_corriente',
  },
  {
    id: 'gr_internet',
    nombre: 'Internet y telefonía de los locales',
    categoria: 'servicios',
    localId: null,
    valor: 714_000,
    iva: 114_000,
    diaDelMes: 12,
    proveedorId: null,
    formaPago: 'debito_automatico',
    diasPlazo: 0,
    cuentaId: 'cta_corriente',
  },
  {
    id: 'gr_vigilancia',
    nombre: 'Vigilancia y monitoreo',
    categoria: 'servicios',
    localId: null,
    valor: 2_380_000,
    iva: 380_000,
    diaDelMes: 3,
    proveedorId: 'pr_vigilancia',
    formaPago: 'cuenta_por_pagar',
    diasPlazo: 7,
    cuentaId: null,
  },
  {
    id: 'gr_contador',
    nombre: 'Honorarios del contador',
    categoria: 'otros',
    localId: null,
    valor: 2_142_000,
    iva: 342_000,
    diaDelMes: 5,
    proveedorId: 'pr_contador',
    formaPago: 'cuenta_por_pagar',
    diasPlazo: 10,
    cuentaId: null,
  },
  {
    id: 'gr_software',
    nombre: 'Software de facturación y nube',
    categoria: 'servicios',
    localId: null,
    valor: 476_000,
    iva: 76_000,
    diaDelMes: 8,
    proveedorId: null,
    formaPago: 'debito_automatico',
    diasPlazo: 0,
    cuentaId: 'cta_corriente',
  },
  {
    id: 'gr_publicidad',
    nombre: 'Pauta en redes sociales',
    categoria: 'publicidad',
    localId: null,
    valor: 3_570_000,
    iva: 570_000,
    diaDelMes: 10,
    proveedorId: 'pr_publicidad',
    formaPago: 'cuenta_por_pagar',
    diasPlazo: 15,
    cuentaId: null,
  },
];

/** Gastos estacionales y ocasionales que siembra el generador (7.10). */
export const GASTOS_OCASIONALES = {
  /** Publicidad extra antes del Día del Padre, Black Friday y diciembre. */
  publicidadEstacional: [
    { mes: 6, valor: 5_950_000, concepto: 'Campaña Día del Padre' },
    { mes: 11, valor: 7_140_000, concepto: 'Campaña Black Friday' },
    { mes: 12, valor: 8_330_000, concepto: 'Campaña de Navidad' },
  ],
  /** Empaques trimestrales (enero, abril, julio, octubre). */
  empaques: { meses: [1, 4, 7, 10], valor: 4_165_000, iva: 665_000, proveedorId: 'pr_empaques' },
  /** Mantenimiento ocasional por local (probabilidad mensual). */
  mantenimiento: { probabilidadMensual: 0.3, rango: [350_000, 1_800_000] as [number, number] },
  /** Comisión de la financiera aliada: se registra como gasto mensual (7.10). */
  comisionFinanciera: { categoria: 'otros' as const, concepto: 'Comisión de la financiera aliada' },
} as const;
