/**
 * Nombres para clientes generados (PLAN 7.7). Nombres y apellidos colombianos comunes, barrios de Bogotá y
 * dominios de correo reservados para ejemplos (nunca le llega un correo a nadie, R14).
 */
export const NOMBRES_HOMBRE = [
  'Andrés',
  'Juan Pablo',
  'Carlos',
  'Santiago',
  'Sebastián',
  'Felipe',
  'Daniel',
  'Alejandro',
  'David',
  'Nicolás',
  'Mauricio',
  'Jorge',
  'Luis Fernando',
  'Ricardo',
  'Óscar',
  'Mateo',
  'Esteban',
  'Camilo',
  'Diego',
  'Juan Esteban',
  'Gabriel',
  'Hernán',
  'Álvaro',
  'Germán',
  'Fabián',
  'Iván',
  'Julián',
  'Rodrigo',
  'Gustavo',
  'Martín',
  'Simón',
  'Tomás',
  'Samuel',
  'Emilio',
  'Francisco',
  'Jaime',
  'Rafael',
  'Eduardo',
  'Mario',
  'Pablo',
  'Héctor',
  'Guillermo',
  'Leonardo',
  'Manuel',
  'Sergio',
  'Javier',
  'Hugo',
  'Cristian',
  'Miguel Ángel',
  'Juan David',
] as const;

/** Algunas clientas compran para su pareja o su familia. */
export const NOMBRES_MUJER = [
  'María José',
  'Catalina',
  'Paula',
  'Natalia',
  'Laura',
  'Carolina',
  'Andrea',
  'Daniela',
  'Juliana',
  'Valeria',
  'Ana María',
  'Mariana',
  'Isabela',
  'Lina',
  'Diana',
  'Claudia',
  'Mónica',
  'Sofía',
  'Alejandra',
  'Ángela',
] as const;

export const APELLIDOS = [
  'Rodríguez',
  'Gómez',
  'González',
  'Martínez',
  'García',
  'López',
  'Hernández',
  'Sánchez',
  'Ramírez',
  'Pérez',
  'Díaz',
  'Torres',
  'Rojas',
  'Vargas',
  'Moreno',
  'Jiménez',
  'Castro',
  'Ruiz',
  'Ortiz',
  'Suárez',
  'Restrepo',
  'Ospina',
  'Zuluaga',
  'Arango',
  'Montoya',
  'Cárdenas',
  'Velásquez',
  'Londoño',
  'Cardona',
  'Salazar',
  'Mejía',
  'Escobar',
  'Echeverry',
  'Botero',
  'Uribe',
  'Valencia',
  'Guzmán',
  'Peñaloza',
  'Quintero',
  'Acosta',
  'Navarro',
  'Rincón',
  'Barrera',
  'Cifuentes',
  'Pardo',
  'Forero',
  'Camacho',
  'Duarte',
  'Bermúdez',
  'Villamizar',
  'Sarmiento',
  'Galvis',
  'Holguín',
  'Lozano',
  'Aristizábal',
  'Gutiérrez',
  'Peñuela',
  'Caicedo',
  'Mendoza',
  'Ríos',
] as const;

export const BARRIOS_BOGOTA = [
  'Chicó',
  'Rosales',
  'Chapinero Alto',
  'Usaquén',
  'Santa Bárbara',
  'Cedritos',
  'Santa Paula',
  'La Cabrera',
  'El Retiro',
  'Antiguo Country',
  'Nicolás de Federmán',
  'Teusaquillo',
  'Salitre',
  'Modelia',
  'Colina Campestre',
  'Niza',
  'Pasadena',
  'Mazurén',
  'Batán',
  'Bella Suiza',
  'Santa Ana',
  'El Nogal',
  'Quinta Camacho',
  'La Soledad',
  'Galerías',
  'Normandía',
  'Hayuelos',
  'Cedro Golf',
  'San Patricio',
  'Lisboa',
] as const;

/** Prefijos móviles colombianos válidos (3XX). */
export const PREFIJOS_CELULAR = [
  '300',
  '301',
  '302',
  '304',
  '305',
  '310',
  '311',
  '312',
  '313',
  '314',
  '315',
  '316',
  '317',
  '318',
  '319',
  '320',
  '321',
  '350',
  '351',
] as const;

/** Dominios reservados para ejemplos. */
export const DOMINIOS_CORREO = ['correo.example', 'mail.example', 'buzon.example'] as const;
